import { mean, percentile, round } from "./utils.mjs";
function safeMean(results, selector) { const values=results.map(selector).filter(v=>Number.isFinite(v)); return values.length?mean(values):null; }
export function estimateCost(result, pricing) { if (!pricing) return 0; return ((Number(result.inputTokens??0)/1e6)*Number(pricing.inputPer1M??0))+((Number(result.outputTokens??0)/1e6)*Number(pricing.outputPer1M??0)); }
export function summarize(results, meta) {
  const runs=results.length, passed=results.filter(r=>r.passed).length, harnessCompleted=results.filter(r=>r.harnessOk).length, crashes=results.filter(r=>!r.timedOut&&r.exitCode!==0).length, timeouts=results.filter(r=>r.timedOut).length, durations=results.map(r=>r.durationMs), firstOutput=results.map(r=>r.firstOutputMs).filter(v=>v!==null&&Number.isFinite(v));
  const byTask=new Map(); for (const result of results) { if(!byTask.has(result.taskId)) byTask.set(result.taskId,[]); byTask.get(result.taskId).push(result); }
  const groups=[...byTask.values()]; const taskCount=groups.length; const passAt1=groups.filter(g=>[...g].sort((a,b)=>a.repeatIndex-b.repeatIndex)[0]?.passed).length; const passAtK=groups.filter(g=>g.some(r=>r.passed)).length; const stable=groups.filter(g=>g.every(r=>r.passed)).length;
  return { schemaVersion:1,generatedAt:new Date().toISOString(),...meta,runs,taskCount,passed,failed:runs-passed,successRate:round(runs?(passed/runs)*100:0,2),harnessCompletionRate:round(runs?(harnessCompleted/runs)*100:0,2),crashRate:round(runs?(crashes/runs)*100:0,2),timeoutRate:round(runs?(timeouts/runs)*100:0,2),passAt1:round(taskCount?(passAt1/taskCount)*100:0,2),passAtK:round(taskCount?(passAtK/taskCount)*100:0,2),stablePassRate:round(taskCount?(stable/taskCount)*100:0,2),durationMs:{mean:round(mean(durations),2),median:round(percentile(durations,50),2),p95:round(percentile(durations,95),2),max:round(Math.max(0,...durations),2)},firstOutputMs:{mean:firstOutput.length?round(mean(firstOutput),2):null,median:firstOutput.length?round(percentile(firstOutput,50),2):null},tokens:{inputMean:round(safeMean(results,r=>Number(r.inputTokens??0))??0,2),outputMean:round(safeMean(results,r=>Number(r.outputTokens??0))??0,2),totalMean:round(safeMean(results,r=>Number(r.totalTokens??0))??0,2)},toolCallsMean:round(safeMean(results,r=>Number(r.toolCalls??0))??0,2),costMean:round(safeMean(results,r=>Number(r.estimatedCost??0))??0,6),peakRssMb:{mean:round(safeMean(results,r=>r.peakRssMb)??0,2),max:round(Math.max(0,...results.map(r=>Number(r.peakRssMb??0))),2)},fileChangesMean:round(safeMean(results,r=>Number(r.fileChanges?.changed??0))??0,2),results };
}
